/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTtsRouteImport } from './routes/admin/tts'
import { Route as AdminScenesRouteImport } from './routes/admin/scenes'
import { Route as AdminMemoryRouteImport } from './routes/admin/memory'
import { Route as AdminLlmRouteImport } from './routes/admin/llm'
import { Route as AdminConversationsRouteImport } from './routes/admin/conversations'
import { Route as AdminAvatarsRouteImport } from './routes/admin/avatars'
import { Route as AdminAnimationsRouteImport } from './routes/admin/animations'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTtsRoute = AdminTtsRouteImport.update({
  id: '/tts',
  path: '/tts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScenesRoute = AdminScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMemoryRoute = AdminMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLlmRoute = AdminLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAvatarsRoute = AdminAvatarsRouteImport.update({
  id: '/avatars',
  path: '/avatars',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnimationsRoute = AdminAnimationsRouteImport.update({
  id: '/animations',
  path: '/animations',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/animations': typeof AdminAnimationsRoute
  '/admin/avatars': typeof AdminAvatarsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/scenes': typeof AdminScenesRoute
  '/admin/tts': typeof AdminTtsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/animations': typeof AdminAnimationsRoute
  '/admin/avatars': typeof AdminAvatarsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/scenes': typeof AdminScenesRoute
  '/admin/tts': typeof AdminTtsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/animations': typeof AdminAnimationsRoute
  '/admin/avatars': typeof AdminAvatarsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/scenes': typeof AdminScenesRoute
  '/admin/tts': typeof AdminTtsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/animations'
    | '/admin/avatars'
    | '/admin/conversations'
    | '/admin/llm'
    | '/admin/memory'
    | '/admin/scenes'
    | '/admin/tts'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/animations'
    | '/admin/avatars'
    | '/admin/conversations'
    | '/admin/llm'
    | '/admin/memory'
    | '/admin/scenes'
    | '/admin/tts'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/animations'
    | '/admin/avatars'
    | '/admin/conversations'
    | '/admin/llm'
    | '/admin/memory'
    | '/admin/scenes'
    | '/admin/tts'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tts': {
      id: '/admin/tts'
      path: '/tts'
      fullPath: '/admin/tts'
      preLoaderRoute: typeof AdminTtsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scenes': {
      id: '/admin/scenes'
      path: '/scenes'
      fullPath: '/admin/scenes'
      preLoaderRoute: typeof AdminScenesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/memory': {
      id: '/admin/memory'
      path: '/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AdminMemoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/llm': {
      id: '/admin/llm'
      path: '/llm'
      fullPath: '/admin/llm'
      preLoaderRoute: typeof AdminLlmRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/avatars': {
      id: '/admin/avatars'
      path: '/avatars'
      fullPath: '/admin/avatars'
      preLoaderRoute: typeof AdminAvatarsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/animations': {
      id: '/admin/animations'
      path: '/animations'
      fullPath: '/admin/animations'
      preLoaderRoute: typeof AdminAnimationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnimationsRoute: typeof AdminAnimationsRoute
  AdminAvatarsRoute: typeof AdminAvatarsRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminLlmRoute: typeof AdminLlmRoute
  AdminMemoryRoute: typeof AdminMemoryRoute
  AdminScenesRoute: typeof AdminScenesRoute
  AdminTtsRoute: typeof AdminTtsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnimationsRoute: AdminAnimationsRoute,
  AdminAvatarsRoute: AdminAvatarsRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminLlmRoute: AdminLlmRoute,
  AdminMemoryRoute: AdminMemoryRoute,
  AdminScenesRoute: AdminScenesRoute,
  AdminTtsRoute: AdminTtsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
